server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nuall_monitor_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    path: ./logs
    max-history: 30
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace