server:
  port: 4567
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/null-monitor-platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true